Eviltask/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls'))
]

Main/urls.py
from django.urls import path, re_path
from django.urls import include
from .views import *

app_name = 'Main'
urlpatterns = [
    path('', view_index, name='index'),
    re_path(r'^topics/$', get_all_topics, name='topics'),
    re_path(r'^topics/(?P<topic_id>\d+)/$', get_topic, name='topic'),
    re_path(r'^create_topic/$', create_topic, name='new_topic'),
    re_path(r'^create_entry/(?P<topic_id>\d+)/$', create_entry, name='create_entry'),
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', edit_entry, name='edit_entry'),


]

Main/models.py
from django.db import models

class Topic(models.Model):
    text = models.CharField(max_length=150)
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    '''Информация, изученная пользователем'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    data_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + '...'

Main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Topic, Entry


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

Main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic
from .models import Entry
from .forms import TopicForm
from .forms import EntryForm
# Create your views here.


def view_index(requests):
    return render(requests, 'index.html')


def get_all_topics(requests):
    """выводим список тем"""
    topics = Topic.objects.order_by('data_added')

    return render(requests, 'topics.html', context={'topics': topics})



def get_topic(requests, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-data_added')
    return render(requests, 'topic.html', context={'topic':topic, 'entries':entries})

def create_topic(request):
    print(request)
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Main:topics'))
    return render(request, 'new_topic.html', context={'form':form})

def create_entry(request, topic_id):
    """Добавляем запись к конкретной теме"""

    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()   # Данные не отправлялись, создаётся пустая форма
    else:
        #Получен POST запрос
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('Main:topic', args=[topic_id]))

    return render(request, 'new_entry.html', context={'topic': topic, 'form': form})

def edit_entry(request, entry_id):
    """Редактирование записей"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Main:topic', args=[topic.id]))

    return render(request, 'edit_entry.html', context={'entry': entry, 'topic': topic, 'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Evil Task</title>
</head>
<body>
<div id="Navbar">
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'Main:index' %}">Evil Task</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Main:topics' %}">Topics</a>
      </li>

    </ul>
  </div>
</nav>
</div>


{% block content %}

{% endblock %}
</body>
</html>

templates/edit_entry.html
{% extends 'base.html' %}
{% block content %}


    <p><a href="{% url 'Main:topic' topic.id%}">{{ topic }}</a></p>

    <h2>Edit entry: </h2>

    <form action="{% url 'Main:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>


    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

templates/new_entry.html
{% extends 'base.html' %}

{% block content %}

<p><a href="{% url 'Main:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add new entry:</p>
    <form action="{% url 'Main:create_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>

    </form>


{% endblock %}

templates/new_topic.html
{% extends 'base.html'%}

{% block content %}
    <h3>Add new topic</h3>

    <form action="{% url 'Main:new_topic' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p}}

      <button  type="submit" class="btn btn-primary">Add topic</button>
</form>
{% endblock %}

templates/topic.html
{% extends 'base.html' %}

{% block content %}


    <p>Topic: {{ topic }}</p>

    <P>Entries: </P>

    {% for entry in entries %}

        <div class="card">
  <div class="card-header">
    Тема
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{ entry.text|linebreaks }}</p>
      <footer class="blockquote-footer">Опубликовано: {{ entry.data_added|date:'M d, Y h:i:s'}}</footer>
      <p>
          <a href="{% url 'Main:edit_entry' entry.id %}">Edit</a>
      </p>
    </blockquote>
  </div>
</div>
        {% empty %}
            <li>There are no entries for this topic yet.</li>

    {% endfor %}
    <a href="{% url 'Main:create_entry' topic.id %}">Add new entry</a>
{% endblock %}

templates/topics.html
{% extends 'base.html' %}


{% block content %}
<p>Topics:</p>

    {% for topic in topics %}


            <a href="{% url 'Main:topic' topic.id %}">{{ topic }}</a>


    {% empty %}
        <li>Dont have topics yet</li>
    {% endfor %}

    <a href="{% url 'Main:new_topic' %}">Add new topic</a>
</ul>


{% endblock %}